@echo off
echo Compiling Jade files...
call jade --out web jade
echo Done. Compiling stylus files...
call stylus --out web\css stylus
echo Done. Compiling coffee files...
call coffee -c --output web\js coffee
echo All done!